# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'comboboxForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(465, 316)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.cbSehirler = QtWidgets.QComboBox(self.centralwidget)
        self.cbSehirler.setGeometry(QtCore.QRect(40, 30, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.cbSehirler.setFont(font)
        self.cbSehirler.setObjectName("cbSehirler")
        self.lblResult = QtWidgets.QLabel(self.centralwidget)
        self.lblResult.setGeometry(QtCore.QRect(250, 40, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lblResult.setFont(font)
        self.lblResult.setText("")
        self.lblResult.setObjectName("lblResult")
        self.btnGetItem = QtWidgets.QPushButton(self.centralwidget)
        self.btnGetItem.setGeometry(QtCore.QRect(80, 100, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btnGetItem.setFont(font)
        self.btnGetItem.setObjectName("btnGetItem")
        self.btnLoadItem = QtWidgets.QPushButton(self.centralwidget)
        self.btnLoadItem.setGeometry(QtCore.QRect(230, 100, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btnLoadItem.setFont(font)
        self.btnLoadItem.setObjectName("btnLoadItem")
        self.btnClearItem = QtWidgets.QPushButton(self.centralwidget)
        self.btnClearItem.setGeometry(QtCore.QRect(80, 160, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btnClearItem.setFont(font)
        self.btnClearItem.setObjectName("btnClearItem")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 465, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnGetItem.setText(_translate("MainWindow", "Get Item"))
        self.btnLoadItem.setText(_translate("MainWindow", "Load Items"))
        self.btnClearItem.setText(_translate("MainWindow", "Clear Item"))
